//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolDBEntities : DbContext
    {
        public SchoolDBEntities()
            : base("name=SchoolDB1")//SchoolDBEntities
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Lesson> Lesson { get; set; }
        public DbSet<Mark> Mark { get; set; }
        public DbSet<Palor> Palor { get; set; }
        public DbSet<Pupil> Pupil { get; set; }
        public DbSet<ReportCard> ReportCard { get; set; }
        public DbSet<Schedule> Schedule { get; set; }
        public DbSet<Teacher> Teacher { get; set; }
    }
}
