//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Palor
    {
        public Palor()
        {
            this.Lesson = new HashSet<Lesson>();
        }
    
        public int Number { get; set; }
        public int FloorNumber { get; set; }
        public int Passport { get; set; }
        public Nullable<int> Capacity { get; set; }
    
        public virtual ICollection<Lesson> Lesson { get; set; }
    }
}
