//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.Lesson = new HashSet<Lesson>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TeacherFK { get; set; }
    
        public virtual ICollection<Lesson> Lesson { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
